library(Seurat)
library(dplyr)
library(cowplot)
library(sctransform)
setwd("E:/00Scientific_Research/Pelvic_Lipomatosis_new/04Singlecelltype_all/02ASPC/")
load("E:/00Scientific_Research/Pelvic_Lipomatosis_new/04Singlecelltype_all/02ASPC/ASPC_new_rename.Rdata")


load("ASPC.Rdata")
DefaultAssay(ASPC) <- "RNA"

pdf("tmp1.pdf",width =6,height = 5)
VlnPlot(ASPC, features = c("AR")
        ,pt.size = 0, combine = FALSE,split.by = "status")
dev.off()
pdf("tmp2.pdf",width =10,height = 9)
plots <-VlnPlot(ASPC, features = c("PTN","AADAC","CIDEA")
                ,pt.size = 0, combine = FALSE,split.by = "status")
CombinePlots(plots = plots, ncol = 1)
dev.off()

pdf("ASC.pdf",width =5,height = 12)
plots <-VlnPlot(ASPC, features = c("CD55","DPP4","MFAP5")
                ,pt.size = 0, combine = FALSE,split.by = "status")
CombinePlots(plots = plots, ncol = 1)
dev.off()


pdf("ICAM1.pdf",width =5,height = 5)
plots <-VlnPlot(ASPC, features = c("ICAM1")
                ,pt.size = 0, combine = FALSE,split.by = "status")
CombinePlots(plots = plots, ncol = 1)
dev.off()

pdf("preA.pdf",width =15,height = 20)
plots <-VlnPlot(ASPC, features = c("ICAM1","PPARG","GGT5","LPL","FABP4","AOC3","MGP","APOD")
                ,pt.size = 0, combine = FALSE,split.by = "status")
CombinePlots(plots = plots, ncol = 1)
dev.off()

pdf("Areg.pdf",width =5,height = 7)
plots <-VlnPlot(ASPC, features = c("F3","CLEC11A","FMO2")
                ,pt.size = 0, combine = FALSE,split.by = "status")
CombinePlots(plots = plots, ncol = 1)
dev.off()

pdf("CD9.pdf",width =5,height = 5)
VlnPlot(ASPC, features = c("CD9")
        ,pt.size = 0, combine = FALSE,split.by = "status")
dev.off()
pdf("AR.pdf",width =4,height = 3)
VlnPlot(ASPC,features = "AR",pt.size = 0,split.by = "status",adjust = 2,y.max = 10,cols = c("#EFC4CE","#2775AB"))
dev.off()

pdf("PTGDS.pdf",width =4,height = 3)
VlnPlot(ASPC,features = "PTGDS",pt.size = 0,split.by = "status",adjust = 2,cols = c("#EFC4CE","#2775AB"))
dev.off()
pdf("ZNF423.pdf",width =4,height = 3)
VlnPlot(ASPC,features = "ZNF423",pt.size = 0,split.by = "status",adjust = 2,cols = c("#EFC4CE","#2775AB"))
dev.off()
pdf("EPAS1.pdf",width =4,height = 3)
VlnPlot(ASPC,features = "EPAS1",pt.size = 0,split.by = "status",adjust = 2,cols = c("#EFC4CE","#2775AB"))
dev.off()
pdf("HIF1A.pdf",width =4,height = 3)
VlnPlot(ASPC,features = "HIF1A",pt.size = 0,split.by = "status",adjust = 2,y.max = 15,cols = c("#EFC4CE","#2775AB"))
dev.off()
pdf("FIP.pdf",width =5,height = 20)
plots <-VlnPlot(ASPC, features = c("ICAM1","CCL2","VCAM1","ITGAM","IL6","CXCL2","CXCL10")
                ,pt.size = 0, combine = FALSE,split.by = "status")
CombinePlots(plots = plots, ncol = 1)
dev.off()
pdf("MAPK.pdf",width =5,height = 9)
plots <-VlnPlot(ASPC, features = c("MAPK1","MAPK3","MAPK8","MAPK9","MAPK10","MAPK14")
                ,pt.size = 0, combine = FALSE,split.by = "status")
CombinePlots(plots = plots, ncol = 2)
dev.off()
FeaturePlot(ASPC, features = c("MAPK1","MAPK3","MAPK8","MAPK9","MAPK10","MAPK14")) 

library(ggsci)
library(ggplot2)
#col=colorRampPalette(pal_npg()(7))(4)
col=c("#F39B7F" ,"#00A087","#8491B4","#7E6148")
#col=c("#E64B35","#8A7284","#62ABBE","#16A79D","#227487","#D3988E","#91D1C2","#859AB6")
#ASPC@active.ident<-factor(ASPC@active.ident,levels=c("Adipocytes","ASPCthelial cells","T/NK cells","Fibroblasts","Neutrophils","Monocytes","Mast cells","B cells"))
plot=DimPlot(ASPC,cols = col)+theme_test()
ggsave(plot,device = "pdf",width = 5,height = 4,filename = "UMAP1_rename_new.pdf") 

#### cell percentage
a <- subset(ASPC, orig.ident =="CWL_Case")
b=as.matrix(table(a@active.ident))
a <- subset(ASPC, orig.ident =="CWL_Control")
b=cbind(b,as.matrix(table(a@active.ident)))
a <- subset(ASPC, orig.ident =="HB_Case")
b=cbind(b,as.matrix(table(a@active.ident)))
a <- subset(ASPC, orig.ident =="LZF_Case")
b=cbind(b,as.matrix(table(a@active.ident)))
a <- subset(ASPC, orig.ident =="LZF_Control")
b=cbind(b,as.matrix(table(a@active.ident)))
a <- subset(ASPC, orig.ident =="ZX_Case")
b=cbind(b,as.matrix(table(a@active.ident)))
a <- subset(ASPC, orig.ident =="ZX_Control")
b=cbind(b,as.matrix(table(a@active.ident)))
a <- subset(ASPC, orig.ident =="ZZL_Case")
b=cbind(b,as.matrix(table(a@active.ident)))
a <- subset(ASPC, orig.ident =="ZZL_Control")
b=cbind(b,as.matrix(table(a@active.ident)))
colnames(b)<-c("CWL_Case","CWL_Control","HB_Case","LZF_Case","LZF_Control","ZX_Case","ZX_Control","ZZL_Case","ZZL_Control")
b<-t(b)
celltype<-rep(colnames(b),each=9)
samples<-rep(rownames(b),4)
Num<-c(b[,1],b[,2],b[,3],b[,4])
Individual<-c()
Status<-c()
for(i in samples){
  Individual<-c(Individual,strsplit(i,"_")[[1]][1])
  Status<-c(Status,strsplit(i,"_")[[1]][2])
}
b<-data.frame(celltype,samples,Num,Individual,Status)
setwd("E:/00Scientific_Research/Pelvic_Lipomatosis_new/04Singlecelltype_all/02ASPC/Cell_percentage_new")
write.table(b,"Cell_percentage.txt",sep = "\t",row.names = F)



